### ISSUE TITLE
Search by ingredients

### ISSUE THREAD

**Issue by jimmykodes** [jimmykodes/recipes#1]
break ingredients into 
```yaml
- amount: text
  item: text
  description: text
```
which renders to 
```html
<div>{{ .Amount }} {{ .Item }} ({{ .Description }})</div>
```

then create do a similar thing with tags where the item from the ingredient can be filtered by so you can see other recipes that use the same ingredient. This may not be that meaningful for something like `cumin` but for `ground beef` this would be great.
