### ISSUE TITLE
do #ref to other recipes

### ISSUE THREAD

**Issue by jimmykodes** [jimmykodes/recipes#3]
Allow linking to other recipes via a `{{ ref other thing }}` so this could be like 
```yaml
title: Chicken Shawarma
ingredients:
  - items:
    - {{ ref garlicky_tahini }}
```
and then the `garlicky_tahini.yaml` file would be linked to
